
default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: 12345678
  host: localhost
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: mini_blog
  password: 12345678

test:
  <<: *default
  database: mini_blog_test
  password: 12345678